<a href="https://colab.research.google.com/github/GavinDowdell/generative_tennis/blob/main/run_tennis_gpt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
try:
    from google.colab import drive
    drive.mount('/content/drive', force_remount=True)
    print("Note: using Google GDrive")
except:
    print("Error, could not mount GDrive")

Mounted at /content/drive
Note: using Google GDrive


# New Section

In [ ]:
import tensorflow as tf
import torch

print(f"TensorFlow Version: {tf.__version__}")
print(f"Pytorch Version: {torch.__version__}")

TensorFlow Version: 2.15.0
Pytorch Version: 2.1.0+cu121


In [ ]:
# prompt: tf.config.list
# check GPU
tf.config.list_physical_devices()


[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Sat Feb  3 01:10:59 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8              10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

# setting device
### The torch.device() function and the device string are both used to specify the device on which a PyTorch tensor should be allocated. However, there are some subtle differences between the two.

### The torch.device() function takes a string as its argument, which can be either "cpu" or "cuda". The "cpu" device represents the CPU, while the "cuda" device represents the GPU. The device string, on the other hand, can be either a string or a number. If it is a string, it must be either "cpu" or "cuda". If it is a number, it represents the index of the GPU to be used.

### In general, it is better to use the torch.device() function to specify the device on which a tensor should be allocated. This is because the torch.device() function is more flexible and can be used to specify any device, including custom devices. The device string, on the other hand, is only valid for the CPU and GPU devices.

### Hence can be a string or a function return however either way need to use the .to method for conversion

In [ ]:
DEVICE = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
DEVICE

device(type='cuda')

In [ ]:
!ls '/content/drive/MyDrive/'

'09 BDS Advanced Calculus 2019.pdf'
'2022fwc_qatar_match_schedule_v34b_11082022_EN_international use.pdf'
'Anyfile Notepad Files'
 Centre_for_WHS_90_day_plan.docx
'Coal Services Senior Data Scientist.docx'
'Colab Notebooks'
'Copy of SVD_presentation.gslides'
 download_trading
 foo.txt
 GDelt.gsheet
'Google AI Studio'
'important backup'
 Jenni
 Jenni_SIP_draft1.docx
 Kaplan_lecturer.docx
 matlab
 miscellaneous
'ML Resources'
'Other python stuff'
 Receipts
 serenity_booking.pdf
'Svd pca_221104_102843.pptx'
'Svd pca_221104_122041.pptx'
'Svd pca_new.pptx'
'Svd presentation _221104_084427.pptx'
 tennis_gpt
'Tennis shot representations.pptx'
'Text mining_221105_135411.pptx'
'Untitled document.docx'


In [ ]:
!ls '/content/drive/MyDrive/tennis_gpt'

gru   mlpmine1	out			     __pycache__  tennis_gpt_colab.py  tennis_shot_data.txt
lstm  mlpmine3	plot_the_embedding_prodn.py  rnn	  tennis_gpt.py        transformer


In [ ]:
import sys
sys.path

['/content',
 '/env/python',
 '/usr/lib/python310.zip',
 '/usr/lib/python3.10',
 '/usr/lib/python3.10/lib-dynload',
 '',
 '/usr/local/lib/python3.10/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/local/lib/python3.10/dist-packages/IPython/extensions',
 '/root/.ipython']

In [ ]:
sys.path.append('/content/drive/MyDrive/tennis_gpt')

In [ ]:
import os
print(os.getcwd())
print(os.listdir('./'))

/content
['.config', 'drive', 'sample_data']


In [ ]:
# run from within ipython = python form outside of ipython
# transformer
%run /content/drive/MyDrive/tennis_gpt/tennis_gpt_colab.py -i /content/drive/MyDrive/tennis_gpt/tennis_shot_data.txt -o /content/drive/MyDrive/tennis_gpt/transformer  --max-steps 10000  --device cuda --type transformer --seed 420


 the inputs are {'input_file': '/content/drive/MyDrive/tennis_gpt/tennis_shot_data.txt', 'work_dir': '/content/drive/MyDrive/tennis_gpt/transformer', 'resume': False, 'sample_only': False, 'max_steps': 10000, 'device': 'cuda', 'seed': 420, 'top_k': -1, 'type': 'transformer', 'n_layer': 4, 'n_head': 4, 'n_embd': 64, 'n_embd2': 64, 'batch_size': 32, 'learning_rate': 0.0005, 'weight_decay': 0.01, 'initial_token': None}.
Enter to continue

 Is cuda available True and device is cuda.
Enter to continue
<class 'dict'>
The input file is /content/drive/MyDrive/tennis_gpt/tennis_shot_data.txt
split up the dataset into 89408 training examples and 22351 test examples
The context length is 86 and the vocab size is 257

number of parameters: 0.22M
model #params: 238464
before getting started lets have a look at a dataset item used to train our transformer on
 (tensor([ 0, 11, 22,  2,  3,  4, 12,  3, 12, 76, 32,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



The final best loss is for transformer is 2.2774598598480225



In [ ]:
# mlp
%run /content/drive/MyDrive/tennis_gpt/tennis_gpt_colab.py -i /content/drive/MyDrive/tennis_gpt/tennis_shot_data.txt -o /content/drive/MyDrive/tennis_gpt/mlpmine1  --max-steps 10000  --device cuda --type mlpmine1 --seed 420


 the inputs are {'input_file': '/content/drive/MyDrive/tennis_gpt/tennis_shot_data.txt', 'work_dir': '/content/drive/MyDrive/tennis_gpt/mlpmine1', 'resume': False, 'sample_only': False, 'max_steps': 10000, 'device': 'cuda', 'seed': 420, 'top_k': -1, 'type': 'mlpmine1', 'n_layer': 4, 'n_head': 4, 'n_embd': 64, 'n_embd2': 64, 'batch_size': 32, 'learning_rate': 0.0005, 'weight_decay': 0.01, 'initial_token': None}.
Enter to continue

 Is cuda available True and device is cuda.
Enter to continue
<class 'dict'>
The input file is /content/drive/MyDrive/tennis_gpt/tennis_shot_data.txt
split up the dataset into 89408 training examples and 22351 test examples
The context length is 86 and the vocab size is 257

model #params: 37313
before getting started lets have a look at a dataset item used to train our mlpmine1 on
 (tensor([ 0, 11, 22,  2,  3,  4, 12,  3, 12, 76, 32,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



The final best loss is for mlpmine1 is 2.295431137084961



In [ ]:
# rnn
%run /content/drive/MyDrive/tennis_gpt/tennis_gpt_colab.py -i /content/drive/MyDrive/tennis_gpt/tennis_shot_data.txt -o /content/drive/MyDrive/tennis_gpt/rnn  --max-steps 10000  --device cuda --type rnn --seed 420


 the inputs are {'input_file': '/content/drive/MyDrive/tennis_gpt/tennis_shot_data.txt', 'work_dir': '/content/drive/MyDrive/tennis_gpt/rnn', 'resume': False, 'sample_only': False, 'max_steps': 10000, 'device': 'cuda', 'seed': 420, 'top_k': -1, 'type': 'rnn', 'n_layer': 4, 'n_head': 4, 'n_embd': 64, 'n_embd2': 64, 'batch_size': 32, 'learning_rate': 0.0005, 'weight_decay': 0.01, 'initial_token': None}.
Enter to continue

 Is cuda available True and device is cuda.
Enter to continue
<class 'dict'>
The input file is /content/drive/MyDrive/tennis_gpt/tennis_shot_data.txt
split up the dataset into 89408 training examples and 22351 test examples
model #params: 41473
before getting started lets have a look at a dataset item used to train our rnn on
 (tensor([ 0, 11, 22,  2,  3,  4, 12,  3, 12, 76, 32,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



The final best loss is for rnn is 2.2695987224578857



In [ ]:
# gru
%run /content/drive/MyDrive/tennis_gpt/tennis_gpt_colab.py -i /content/drive/MyDrive/tennis_gpt/tennis_shot_data.txt -o /content/drive/MyDrive/tennis_gpt/gru  --max-steps 10000  --device cuda --type gru --seed 420


 the inputs are {'input_file': '/content/drive/MyDrive/tennis_gpt/tennis_shot_data.txt', 'work_dir': '/content/drive/MyDrive/tennis_gpt/gru', 'resume': False, 'sample_only': False, 'max_steps': 10000, 'device': 'cuda', 'seed': 420, 'top_k': -1, 'type': 'gru', 'n_layer': 4, 'n_head': 4, 'n_embd': 64, 'n_embd2': 64, 'batch_size': 32, 'learning_rate': 0.0005, 'weight_decay': 0.01, 'initial_token': None}.
Enter to continue

 Is cuda available True and device is cuda.
Enter to continue
<class 'dict'>
The input file is /content/drive/MyDrive/tennis_gpt/tennis_shot_data.txt
split up the dataset into 89408 training examples and 22351 test examples
model #params: 58113
before getting started lets have a look at a dataset item used to train our gru on
 (tensor([ 0, 11, 22,  2,  3,  4, 12,  3, 12, 76, 32,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



The final best loss is for gru is 2.2708587646484375



In [ ]:
# lstm
%run /content/drive/MyDrive/tennis_gpt/tennis_gpt_colab.py -i /content/drive/MyDrive/tennis_gpt/tennis_shot_data.txt -o /content/drive/MyDrive/tennis_gpt/lstm  --max-steps 10000  --device cuda --type lstm --seed 420


 the inputs are {'input_file': '/content/drive/MyDrive/tennis_gpt/tennis_shot_data.txt', 'work_dir': '/content/drive/MyDrive/tennis_gpt/lstm', 'resume': False, 'sample_only': False, 'max_steps': 10000, 'device': 'cuda', 'seed': 420, 'top_k': -1, 'type': 'lstm', 'n_layer': 4, 'n_head': 4, 'n_embd': 64, 'n_embd2': 64, 'batch_size': 32, 'learning_rate': 0.0005, 'weight_decay': 0.01, 'initial_token': None}.
Enter to continue

 Is cuda available True and device is cuda.
Enter to continue
<class 'dict'>
The input file is /content/drive/MyDrive/tennis_gpt/tennis_shot_data.txt
split up the dataset into 89408 training examples and 22351 test examples
model #params: 66433
before getting started lets have a look at a dataset item used to train our lstm on
 (tensor([ 0, 11, 22,  2,  3,  4, 12,  3, 12, 76, 32,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
  

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



The final best loss is for lstm is 2.2662150859832764



In [ ]:
# trigrams mlp
%run /content/drive/MyDrive/tennis_gpt/tennis_gpt_colab.py -i /content/drive/MyDrive/tennis_gpt/tennis_shot_data.txt -o /content/drive/MyDrive/tennis_gpt/mlpmine3  --max-steps 10000  --device cuda --type mlpmine3 --seed 420


 the inputs are {'input_file': '/content/drive/MyDrive/tennis_gpt/tennis_shot_data.txt', 'work_dir': '/content/drive/MyDrive/tennis_gpt/mlpmine3', 'resume': False, 'sample_only': False, 'max_steps': 10000, 'device': 'cuda', 'seed': 420, 'top_k': -1, 'type': 'mlpmine3', 'n_layer': 4, 'n_head': 4, 'n_embd': 64, 'n_embd2': 64, 'batch_size': 32, 'learning_rate': 0.0005, 'weight_decay': 0.01, 'initial_token': None}.
Enter to continue

 Is cuda available True and device is cuda.
Enter to continue
<class 'dict'>
The input file is /content/drive/MyDrive/tennis_gpt/tennis_shot_data.txt
split up the dataset into 89408 training examples and 22351 test examples
model #params: 45505
before getting started lets have a look at a dataset item used to train our mlpmine3 on
 (tensor([ 0, 11, 22,  2,  3,  4, 12,  3, 12, 76, 32,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



The final best loss is for mlpmine3 is 2.258105516433716



In [ ]:
a = torch.tensor([1,2])

In [ ]:
a.device

device(type='cpu')

In [ ]:
# in this case device is a string not a function return from device
a.to('cuda')

tensor([1, 2], device='cuda:0')

In [ ]:
a.dtype

torch.int64

In [ ]:
a.requires_grad

False

In [ ]:
a.cpu()

tensor([1, 2])

In [ ]:
a.device

device(type='cpu')